name: CI project

on:
  push:
    branches:
      - main
  pull_request:

  release:
    types: [published]

jobs:
  reassure:
    permissions:
      contents: write
    name: Make me happy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cat files
        run: |
          cat file_1.txt
          cat file_2.txt

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: |
            file_1.txt
            file_2.txt
